//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacesDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneMonitoring
    {
        public int ID { get; set; }
        public int BasketID { get; set; }
        public int ZoneID { get; set; }
        public System.DateTime EntranceTimestamp { get; set; }
        public Nullable<System.DateTime> ExitTimestamp { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
