//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacesApiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Face
    {
        public int ID { get; set; }
        public Nullable<double> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> Eyeglasses { get; set; }
        public Nullable<double> Beard { get; set; }
        public Nullable<double> Mustaches { get; set; }
        public string Faceid { get; set; }
        public System.DateTime EntranceTimestamp { get; set; }
        public int EntranceCamera { get; set; }
        public Nullable<System.DateTime> ExitTimestamp { get; set; }
        public Nullable<int> ExitCamera { get; set; }
        public bool IsDeduplicated { get; set; }
        public Nullable<int> VisitDurationInSeconds { get; set; }
    
        public virtual StoreTree Entrance_Camera { get; set; }
        public virtual StoreTree Exit_Camera { get; set; }
    }
}
